name: iuapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #aqui se agregar los archivos extraibles para todo el proyecto
  assets:
    - assets/
    - assets/carousel/
